services:
  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: daily-diet
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    
volumes:
  db-data:
    driver: local